name: Build Frontend

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Run build
        run: cd frontend && npm run build